language: generic
os:
- linux
- osx
osx_image: xcode6.4
dist: trusty
sudo: required

env:
  - MPLBACKEND='Agg' OMP_NUM_THREADS=1 MKL_NUM_THREADS=1 NUMEXPR_NUM_THREADS=1 PATH="${HOME}/miniconda/bin:${PATH}"

cache:
  directories:
    - $HOME/download
    - $HOME/miniconda
  timeout: 1000

before_install:
  - echo "listing home"
  - ls $HOME
  - echo "end of listing"
  - source ci/install_miniconda.sh

install:
  - source ci/install_package.sh

script:
  - while sleep 540; do echo "=====[ $SECONDS seconds still running ]====="; done &
  - python -m pytest -vv --cov=hawc_hal
  - kill %1
  - conda clean -y -a
  - pip uninstall hawc_hal -y

after_success:
  - codecov

before_cache:
  - if ! [[ $TRAVIS_TAG ]]; then rm -rf $HOME/miniconda/conda-bld; fi
  - conda clean -y -a
  - rm -rf $HOME/miniconda/locks $HOME/miniconda/pkgs $HOME/miniconda/var $HOME/miniconda/conda-meta/history
